/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MasterChefV3 } from "./MasterChefV3";

export { MasterChefV3__factory } from "./factories/MasterChefV3__factory";
